-- MySQL 8.0 full schema for Chtholly Hub.
-- Development bootstrap file generated by consolidating db/migration/V0..V19.
-- Incremental ALTER/RENAME migrations are represented here as final table shapes
-- so a new empty database can be initialized with one script.

-- V0__schema_migrations.sql: local migration bookkeeping.
CREATE TABLE IF NOT EXISTS schema_migrations (
    version VARCHAR(64) NOT NULL,
    applied_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Base auth/profile schema + V3 handle rename + V12 admin role/ban fields.
CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    phone VARCHAR(32) NULL,
    email VARCHAR(128) NULL,
    password_hash VARCHAR(128) NULL,
    nickname VARCHAR(64) NOT NULL,
    avatar TEXT NULL,
    bio VARCHAR(512) NULL,
    handle VARCHAR(64) NULL COMMENT 'User unique @handle',
    gender VARCHAR(16) NULL,
    birthday DATE NULL,
    school VARCHAR(128) NULL,
    tags_json JSON NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'USER',
    banned_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_users_phone (phone),
    UNIQUE KEY uk_users_email (email),
    UNIQUE KEY uk_users_handle (handle)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Base login audit + V13 failure reason.
CREATE TABLE IF NOT EXISTS login_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NULL,
    identifier VARCHAR(128) NOT NULL,
    channel VARCHAR(32) NOT NULL,
    ip VARCHAR(45) NULL,
    user_agent VARCHAR(512) NULL,
    status VARCHAR(16) NOT NULL COMMENT 'SUCCESS / FAILED',
    failure_reason VARCHAR(64) NULL COMMENT 'WRONG_PASSWORD / ACCOUNT_LOCKED / ACCOUNT_NOT_FOUND',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY ix_login_logs_user_created_at (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- V5__tags.sql: tag catalog used alongside posts.tags JSON.
CREATE TABLE IF NOT EXISTS tags (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(64) NOT NULL COMMENT 'Display name',
    slug VARCHAR(128) NOT NULL COMMENT 'URL slug',
    creator_id BIGINT UNSIGNED NULL COMMENT 'Optional creator user id',
    usage_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Published post usage count',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_tags_name (name),
    UNIQUE KEY uk_tags_slug (slug),
    KEY ix_tags_usage (usage_count DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- V3__rename_posts_and_handle.sql + V4__add_slug.sql + V15 content analysis.
-- Legacy know_posts is represented as the final posts table here.
CREATE TABLE IF NOT EXISTS posts (
    id BIGINT UNSIGNED NOT NULL,
    tag_id BIGINT UNSIGNED NULL COMMENT 'Primary category id',
    tags JSON NULL COMMENT 'Tag name array, e.g. ["java", "anime"]',
    title VARCHAR(256) NULL,
    slug VARCHAR(128) NULL COMMENT 'URL friendly identifier',
    description VARCHAR(50) NULL COMMENT 'Short summary',
    content_url TEXT NULL COMMENT 'OSS content URL or signed URL',
    content_object_key VARCHAR(512) NULL COMMENT 'OSS object key',
    content_etag VARCHAR(128) NULL COMMENT 'OSS ETag',
    content_size BIGINT UNSIGNED NULL COMMENT 'Markdown byte size',
    content_sha256 CHAR(64) NULL COMMENT 'Markdown SHA-256 hex',
    creator_id BIGINT UNSIGNED NOT NULL,
    is_top TINYINT(1) NOT NULL DEFAULT 0,
    type VARCHAR(32) NOT NULL DEFAULT 'image_text',
    visible VARCHAR(32) NOT NULL DEFAULT 'public',
    img_urls JSON NULL COMMENT 'Image URL array',
    video_url TEXT NULL COMMENT 'Reserved video URL',
    status VARCHAR(16) NOT NULL DEFAULT 'draft',
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    publish_time TIMESTAMP NULL DEFAULT NULL,
    content_analysis JSON NULL COMMENT 'Agent content understanding result',
    content_analyzed_at DATETIME(3) NULL COMMENT 'Last Agent content understanding time',
    PRIMARY KEY (id),
    UNIQUE KEY uk_posts_slug (slug),
    KEY ix_posts_creator_ct (creator_id, create_time),
    KEY ix_posts_status_ct (status, create_time),
    KEY ix_posts_tag_ct (tag_id, create_time),
    KEY ix_posts_top_ct (is_top, create_time),
    KEY ix_posts_creator_status_pub (creator_id, status, publish_time),
    CONSTRAINT fk_posts_creator FOREIGN KEY (creator_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Explicitly approved, synchronous draft-edit previews.
CREATE TABLE IF NOT EXISTS draft_edit_preview (
    id BIGINT UNSIGNED NOT NULL,
    owner_id BIGINT UNSIGNED NOT NULL,
    draft_id BIGINT UNSIGNED NOT NULL,
    skill_id VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    skill_version VARCHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    base_content_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    candidate_content MEDIUMTEXT NOT NULL,
    candidate_content_sha256 CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    preview_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    status VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    created_at DATETIME(3) NOT NULL,
    expires_at DATETIME(3) NOT NULL,
    decided_at DATETIME(3) NULL,
    PRIMARY KEY (id),
    KEY ix_draft_edit_owner_draft (owner_id, draft_id, created_at),
    KEY ix_draft_edit_expiry (status, expires_at),
    CONSTRAINT fk_draft_edit_owner FOREIGN KEY (owner_id) REFERENCES users(id),
    CONSTRAINT fk_draft_edit_draft FOREIGN KEY (draft_id) REFERENCES posts(id),
    CONSTRAINT ck_draft_edit_status CHECK (status IN ('PENDING', 'APPLIED', 'REJECTED', 'EXPIRED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Base outbox table for CDC-style asynchronous work.
CREATE TABLE IF NOT EXISTS outbox (
    id BIGINT UNSIGNED NOT NULL,
    aggregate_type VARCHAR(64) NOT NULL,
    aggregate_id BIGINT UNSIGNED NULL,
    type VARCHAR(64) NOT NULL,
    payload JSON NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY ix_outbox_agg (aggregate_type, aggregate_id),
    KEY ix_outbox_ct (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Durable idempotency for counter events and their convergent MySQL snapshots.
CREATE TABLE IF NOT EXISTS counter_event_inbox (
    event_id VARCHAR(128) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    entity_type VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    entity_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    metric VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    delta INT NOT NULL,
    user_id BIGINT NOT NULL,
    fact_epoch BIGINT UNSIGNED NOT NULL,
    applied_at DATETIME(3) NOT NULL,
    PRIMARY KEY (event_id),
    KEY ix_counter_inbox_entity (entity_type, entity_id, metric, applied_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS counter_snapshot (
    entity_type VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    entity_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
    metric VARCHAR(16) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
    count_value BIGINT NOT NULL,
    fact_epoch BIGINT UNSIGNED NOT NULL DEFAULT 0,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (entity_type, entity_id, metric),
    KEY ix_counter_snapshot_updated (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Relation write/read models.
CREATE TABLE IF NOT EXISTS following (
    id BIGINT UNSIGNED NOT NULL,
    from_user_id BIGINT UNSIGNED NOT NULL,
    to_user_id BIGINT UNSIGNED NOT NULL,
    rel_status TINYINT NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_from_to (from_user_id, to_user_id),
    KEY idx_from_created (from_user_id, created_at, to_user_id, rel_status),
    KEY idx_to (to_user_id, from_user_id, rel_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS follower (
    id BIGINT UNSIGNED NOT NULL,
    to_user_id BIGINT UNSIGNED NOT NULL,
    from_user_id BIGINT UNSIGNED NOT NULL,
    rel_status TINYINT NOT NULL DEFAULT 1,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_to_from (to_user_id, from_user_id),
    KEY idx_to_created (to_user_id, created_at, from_user_id, rel_status),
    KEY idx_from (from_user_id, to_user_id, rel_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- V6__comments.sql + V9 soft delete + V16 Chtholly AI comment flag.
CREATE TABLE IF NOT EXISTS comments (
    id BIGINT UNSIGNED NOT NULL,
    post_id BIGINT UNSIGNED NOT NULL,
    parent_id BIGINT UNSIGNED NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    content VARCHAR(2000) NOT NULL,
    is_chtholly TINYINT(1) NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at DATETIME DEFAULT NULL,
    updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY ix_comments_post_ct (post_id, created_at),
    KEY ix_comments_parent (parent_id),
    KEY idx_comments_chtholly_created (is_chtholly, created_at),
    CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts(id),
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- V7__notifications.sql + V10 cleanup index.
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    type VARCHAR(32) NOT NULL,
    payload JSON NOT NULL,
    read_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY ix_notifications_user_ct (user_id, created_at DESC),
    KEY ix_notifications_user_unread (user_id, read_at),
    KEY idx_cleanup (read_at, created_at),
    CONSTRAINT fk_notifications_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- V8__bangumi_tables.sql: local Bangumi metadata cache for Agent tools.
CREATE TABLE IF NOT EXISTS bangumi_subjects (
    id BIGINT UNSIGNED NOT NULL COMMENT 'Bangumi subject id',
    type TINYINT NOT NULL DEFAULT 2 COMMENT '1=book, 2=anime, 3=music, 4=game, 6=real',
    name VARCHAR(255) NOT NULL,
    name_cn VARCHAR(255) NULL,
    summary TEXT NULL,
    nsfw TINYINT(1) NOT NULL DEFAULT 0,
    air_date DATE NULL,
    score DECIMAL(4, 2) NULL,
    `rank` INT NULL,
    eps_count INT NULL,
    raw_json JSON NULL,
    synced_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    FULLTEXT KEY ft_bangumi_name (name, name_cn)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bangumi_episodes (
    id BIGINT UNSIGNED NOT NULL COMMENT 'Bangumi episode id',
    subject_id BIGINT UNSIGNED NOT NULL,
    ep INT NULL,
    sort_num INT NOT NULL DEFAULT 0,
    name VARCHAR(255) NULL,
    air_date DATE NULL,
    synced_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY ix_bgm_ep_subject (subject_id),
    CONSTRAINT fk_bgm_ep_subject FOREIGN KEY (subject_id) REFERENCES bangumi_subjects(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS bangumi_sync_log (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    subject_id BIGINT UNSIGNED NOT NULL,
    action VARCHAR(32) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY ix_bgm_sync_subject (subject_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- V11__dead_letter_messages.sql: Kafka consumer failure records.
CREATE TABLE IF NOT EXISTS dead_letter_messages (
    id BIGINT UNSIGNED NOT NULL,
    source_topic VARCHAR(100) NOT NULL,
    message_key VARCHAR(255) NULL,
    message_value TEXT NOT NULL,
    exception_class VARCHAR(255) NULL,
    exception_message TEXT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    status ENUM('PENDING', 'RETRYING', 'DEAD') NOT NULL DEFAULT 'PENDING',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_topic_status (source_topic, status),
    KEY idx_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- V12__admin_roles_and_audit.sql: admin operation audit log.
CREATE TABLE IF NOT EXISTS admin_audit_logs (
    id BIGINT NOT NULL,
    admin_user_id BIGINT NOT NULL,
    action VARCHAR(50) NOT NULL,
    target_type VARCHAR(50) NULL,
    target_id BIGINT NULL,
    detail JSON NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_admin (admin_user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- V14__archived_experiences.sql: long-term Agent experience archive.
CREATE TABLE IF NOT EXISTS archived_experiences (
    id BIGINT NOT NULL AUTO_INCREMENT,
    text TEXT NOT NULL,
    importance INT NOT NULL,
    source VARCHAR(64) NOT NULL,
    created_at DATETIME(3) NOT NULL,
    archived_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    KEY idx_archived_experiences_created_at (created_at),
    KEY idx_archived_experiences_importance (importance)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Knowledge graph adjacency tables: entities are searched in ES and traversed in MySQL.
CREATE TABLE IF NOT EXISTS knowledge_entities (
    id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(32) NOT NULL COMMENT 'PERSON / WORK / CONCEPT / TAG',
    description TEXT NULL,
    aliases JSON NULL,
    embedding TEXT NULL COMMENT 'Serialized vector text for later similarity calculation',
    metadata JSON NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_knowledge_entities_name_type (name, type),
    KEY idx_knowledge_entities_type (type),
    KEY idx_knowledge_entities_updated_at (updated_at),
    FULLTEXT KEY ft_knowledge_entities_name_desc (name, description)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS knowledge_relations (
    id BIGINT UNSIGNED NOT NULL,
    source_entity_id BIGINT UNSIGNED NOT NULL,
    target_entity_id BIGINT UNSIGNED NOT NULL,
    relation_type VARCHAR(32) NOT NULL COMMENT 'APPEARS_IN / RELATED_TO / RECOMMENDS / CREATED_BY',
    weight DOUBLE NOT NULL DEFAULT 1.0,
    metadata JSON NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_knowledge_relations_edge (source_entity_id, target_entity_id, relation_type),
    KEY idx_knowledge_relations_source_weight (source_entity_id, weight),
    KEY idx_knowledge_relations_target (target_entity_id),
    CONSTRAINT fk_knowledge_relations_source FOREIGN KEY (source_entity_id) REFERENCES knowledge_entities(id),
    CONSTRAINT fk_knowledge_relations_target FOREIGN KEY (target_entity_id) REFERENCES knowledge_entities(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- V17__add_execution_traces.sql: Agent execution trace persistence.
CREATE TABLE IF NOT EXISTS execution_traces (
    id BIGINT NOT NULL AUTO_INCREMENT,
    correlation_id VARCHAR(64) NOT NULL,
    user_id BIGINT NULL,
    session_id VARCHAR(128) NULL,
    started_at DATETIME(3) NOT NULL,
    finished_at DATETIME(3) NULL,
    duration_ms INT NULL,
    status ENUM('SUCCESS', 'FAILURE', 'TIMEOUT', 'ABORTED') NOT NULL,
    steps_count INT NOT NULL DEFAULT 0,
    tool_calls JSON NULL,
    error_message TEXT NULL,
    input_tokens INT NOT NULL DEFAULT 0,
    output_tokens INT NOT NULL DEFAULT 0,
    trace_payload JSON NOT NULL,
    pattern_analyzed TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_correlation_id (correlation_id),
    KEY idx_user_id (user_id),
    KEY idx_status (status),
    KEY idx_started_at (started_at),
    KEY idx_pattern_analyzed (pattern_analyzed, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS trace_failure_patterns (
    id BIGINT NOT NULL AUTO_INCREMENT,
    pattern_key VARCHAR(256) NOT NULL,
    occurrence_count INT NOT NULL DEFAULT 1,
    last_seen_at DATETIME(3) NOT NULL,
    sample_trace_ids JSON NULL,
    resolution_hint TEXT NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (id),
    UNIQUE KEY uk_pattern (pattern_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- V19__seed_recommendations.sql: Bangumi recommendation wall and seed idempotency.
CREATE TABLE IF NOT EXISTS bangumi_recommendations (
    bangumi_id BIGINT UNSIGNED NOT NULL,
    title VARCHAR(255) NOT NULL,
    title_cn VARCHAR(255) NULL,
    cover_url TEXT NULL,
    score DECIMAL(4, 2) NULL,
    chtholly_review TEXT NOT NULL,
    tags_json JSON NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (bangumi_id),
    KEY ix_bgm_rec_score (score),
    KEY ix_bgm_rec_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS seed_data (
    seed_key VARCHAR(64) NOT NULL,
    summary_json JSON NULL,
    created_at DATETIME(3) NOT NULL,
    PRIMARY KEY (seed_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- V22__seed_content_identity.sql: immutable seed-key to entity identity mapping.
CREATE TABLE IF NOT EXISTS seed_content_identity (
    namespace VARCHAR(64) NOT NULL,
    entity_type VARCHAR(16) NOT NULL,
    seed_key VARCHAR(128) NOT NULL,
    entity_id BIGINT UNSIGNED NOT NULL,
    pack_version VARCHAR(64) NOT NULL,
    content_hash CHAR(64) NULL,
    metadata JSON NULL,
    created_at DATETIME(3) NOT NULL,
    updated_at DATETIME(3) NOT NULL,
    PRIMARY KEY (namespace, entity_type, seed_key),
    UNIQUE KEY uk_seed_identity_entity (entity_type, entity_id),
    KEY ix_seed_identity_version (pack_version, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- V5 seed tags.
INSERT INTO tags (name, slug, usage_count) VALUES
    ('动漫', '动漫', 1),
    ('推荐', '推荐', 1),
    ('番剧', '番剧', 1),
    ('珂朵莉', '珂朵莉', 1)
ON DUPLICATE KEY UPDATE
    usage_count = GREATEST(usage_count, VALUES(usage_count)),
    updated_at = NOW();

-- V16/V18 Chtholly bot user seed.
-- V16 originally used id=2. V18 moved the bot to a dedicated high id to avoid
-- conflicts with early registered users; the consolidated schema keeps only
-- the final dedicated bot identity.
SET @chtholly_bot_id = 888888888888888888;

INSERT INTO users (id, nickname, avatar, bio, handle, created_at, updated_at)
VALUES (
    @chtholly_bot_id,
    '珂朵莉',
    NULL,
    '仓库里的珂朵莉',
    'chtholly',
    NOW(),
    NOW()
)
ON DUPLICATE KEY UPDATE
    nickname = VALUES(nickname),
    bio = VALUES(bio),
    handle = VALUES(handle);
